// AUTO-EXTRACTED from Prismic (thevertmenthe.cdn.prismic.io) — 44 artworks.
// Order matches the original site: importance desc, then publication date desc.
export type TvArticle = {
  uid: string
  title: string
  importance: "high" | "medium" | "low"
  vendu: boolean
  image: string
  size: string
  technique: string
  year: string
  notesTop: string[]
  notesBottom: string[]
}

export const TV_ARTICLES: TvArticle[] = [
  {
    uid: "six-forty-seven",
    title: "Six Forty Seven",
    importance: "medium" as TvArticle['importance'],
    vendu: false,
    image: "/thevertmenthe/artworks/six-forty-seven.png",
    size: "14.8 * 21 cm",
    technique: "",
    year: "2025",
    notesTop: [],
    notesBottom: [],
  },
  {
    uid: "echos",
    title: "Echos",
    importance: "medium" as TvArticle['importance'],
    vendu: false,
    image: "/thevertmenthe/artworks/echos.png",
    size: "14.8 * 21 cm",
    technique: "",
    year: "2025",
    notesTop: [],
    notesBottom: [],
  },
  {
    uid: "sun-flower",
    title: "Sun flower",
    importance: "medium" as TvArticle['importance'],
    vendu: false,
    image: "/thevertmenthe/artworks/sun-flower.png",
    size: "14.8 * 21 cm",
    technique: "",
    year: "2025",
    notesTop: [],
    notesBottom: [],
  },
  {
    uid: "realization",
    title: "Realization",
    importance: "medium" as TvArticle['importance'],
    vendu: false,
    image: "/thevertmenthe/artworks/realization.png",
    size: "14.8 * 21 cm",
    technique: "",
    year: "2025",
    notesTop: [],
    notesBottom: [],
  },
  {
    uid: "paradise",
    title: "Paradise",
    importance: "medium" as TvArticle['importance'],
    vendu: true,
    image: "/thevertmenthe/artworks/paradise.png",
    size: "14.8 * 21 cm",
    technique: "",
    year: "2025",
    notesTop: [],
    notesBottom: [],
  },
  {
    uid: "untilted",
    title: "Untilted",
    importance: "medium" as TvArticle['importance'],
    vendu: false,
    image: "/thevertmenthe/artworks/untilted.png",
    size: "14.8 * 21 cm",
    technique: "",
    year: "2025",
    notesTop: [],
    notesBottom: [],
  },
  {
    uid: "not-allowed",
    title: "Not allowed",
    importance: "medium" as TvArticle['importance'],
    vendu: false,
    image: "/thevertmenthe/artworks/not-allowed.png",
    size: "21 * 29.7 cm",
    technique: "",
    year: "2025",
    notesTop: [],
    notesBottom: [],
  },
  {
    uid: "no-suprises",
    title: "No suprises",
    importance: "medium" as TvArticle['importance'],
    vendu: false,
    image: "/thevertmenthe/artworks/no-suprises.png",
    size: "21 * 29.7 cm",
    technique: "",
    year: "2025",
    notesTop: [],
    notesBottom: [],
  },
  {
    uid: "apple",
    title: "Apple",
    importance: "medium" as TvArticle['importance'],
    vendu: false,
    image: "/thevertmenthe/artworks/apple.png",
    size: "21 * 29.7 cm",
    technique: "",
    year: "2025",
    notesTop: [],
    notesBottom: [],
  },
  {
    uid: "cooked",
    title: "Cooked",
    importance: "medium" as TvArticle['importance'],
    vendu: false,
    image: "/thevertmenthe/artworks/cooked.png",
    size: "21 * 29.7 cm",
    technique: "",
    year: "2025",
    notesTop: [],
    notesBottom: [],
  },
  {
    uid: "good-man",
    title: "Good man",
    importance: "medium" as TvArticle['importance'],
    vendu: false,
    image: "/thevertmenthe/artworks/good-man.png",
    size: "14.8 * 21 cm",
    technique: "",
    year: "2025",
    notesTop: [],
    notesBottom: [],
  },
  {
    uid: "like-a-leaf",
    title: "Like a leaf",
    importance: "medium" as TvArticle['importance'],
    vendu: false,
    image: "/thevertmenthe/artworks/like-a-leaf.png",
    size: "21 * 29.7 cm",
    technique: "",
    year: "2025",
    notesTop: [],
    notesBottom: [],
  },
  {
    uid: "queens-kiss",
    title: "Queen's kiss",
    importance: "medium" as TvArticle['importance'],
    vendu: false,
    image: "/thevertmenthe/artworks/queens-kiss.png",
    size: " 21 * 29.7 cm",
    technique: "",
    year: "2025",
    notesTop: [],
    notesBottom: [],
  },
  {
    uid: "space-world",
    title: "Space world",
    importance: "medium" as TvArticle['importance'],
    vendu: true,
    image: "/thevertmenthe/artworks/space-world.png",
    size: "21 * 29.7",
    technique: "",
    year: "2025",
    notesTop: [],
    notesBottom: [],
  },
  {
    uid: "hands",
    title: "Hands",
    importance: "medium" as TvArticle['importance'],
    vendu: true,
    image: "/thevertmenthe/artworks/hands.png",
    size: "21 * 29.7 cm",
    technique: "",
    year: "2025",
    notesTop: [],
    notesBottom: [],
  },
  {
    uid: "sweet",
    title: "Sweet",
    importance: "medium" as TvArticle['importance'],
    vendu: false,
    image: "/thevertmenthe/artworks/sweet.png",
    size: "21 * 29.7cm",
    technique: "",
    year: "2025",
    notesTop: [],
    notesBottom: [],
  },
  {
    uid: "levitate",
    title: "Levitate",
    importance: "medium" as TvArticle['importance'],
    vendu: false,
    image: "/thevertmenthe/artworks/levitate.png",
    size: "21 * 29.7 cm",
    technique: "",
    year: "2025",
    notesTop: [],
    notesBottom: [],
  },
  {
    uid: "at-eternitys-gates",
    title: "At eternity's gates",
    importance: "medium" as TvArticle['importance'],
    vendu: false,
    image: "/thevertmenthe/artworks/at-eternitys-gates.png",
    size: "21 * 29.7 cm",
    technique: "",
    year: "2025",
    notesTop: [],
    notesBottom: [],
  },
  {
    uid: "jungle",
    title: "Jungle",
    importance: "medium" as TvArticle['importance'],
    vendu: false,
    image: "/thevertmenthe/artworks/jungle.png",
    size: "21 * 29.7 cm",
    technique: "",
    year: "2025",
    notesTop: [],
    notesBottom: [],
  },
  {
    uid: "venus",
    title: "Venus",
    importance: "medium" as TvArticle['importance'],
    vendu: true,
    image: "/thevertmenthe/artworks/venus.png",
    size: "21 * 29.7 cm",
    technique: "",
    year: "2025",
    notesTop: [],
    notesBottom: [],
  },
  {
    uid: "medieval-journey",
    title: "Medieval journey",
    importance: "medium" as TvArticle['importance'],
    vendu: true,
    image: "/thevertmenthe/artworks/medieval-journey.png",
    size: "21 * 29.7 cm",
    technique: "",
    year: "2025",
    notesTop: [],
    notesBottom: [],
  },
  {
    uid: "mines-of-moria",
    title: "Mines of Moria",
    importance: "medium" as TvArticle['importance'],
    vendu: false,
    image: "/thevertmenthe/artworks/mines-of-moria.png",
    size: "21 * 29.7 cm",
    technique: "",
    year: "2025",
    notesTop: [],
    notesBottom: [],
  },
  {
    uid: "deep-swim",
    title: "Deep swim",
    importance: "medium" as TvArticle['importance'],
    vendu: false,
    image: "/thevertmenthe/artworks/deep-swim.png",
    size: "21 * 29.7 cm",
    technique: "",
    year: "2025",
    notesTop: [],
    notesBottom: [],
  },
  {
    uid: "snowy",
    title: "Snowy",
    importance: "medium" as TvArticle['importance'],
    vendu: false,
    image: "/thevertmenthe/artworks/snowy.png",
    size: "21 * 29.7 cm",
    technique: "",
    year: "2025",
    notesTop: [],
    notesBottom: [],
  },
  {
    uid: "level-0",
    title: "Level 0",
    importance: "medium" as TvArticle['importance'],
    vendu: false,
    image: "/thevertmenthe/artworks/level-0.png",
    size: "21 * 29.7 cm",
    technique: "",
    year: "2025",
    notesTop: [],
    notesBottom: [],
  },
  {
    uid: "ryuk",
    title: "Ryuk",
    importance: "medium" as TvArticle['importance'],
    vendu: false,
    image: "/thevertmenthe/artworks/ryuk.png",
    size: "21 * 29.7 cm",
    technique: "",
    year: "2025",
    notesTop: [],
    notesBottom: [],
  },
  {
    uid: "shine",
    title: "Shine",
    importance: "medium" as TvArticle['importance'],
    vendu: true,
    image: "/thevertmenthe/artworks/shine.png",
    size: "21 * 29.7 cm",
    technique: "",
    year: "2025",
    notesTop: [],
    notesBottom: [],
  },
  {
    uid: "breakfast",
    title: "Breakfast",
    importance: "medium" as TvArticle['importance'],
    vendu: false,
    image: "/thevertmenthe/artworks/breakfast.png",
    size: "21 * 29.7 cm",
    technique: "",
    year: "2025",
    notesTop: [],
    notesBottom: [],
  },
  {
    uid: "apocalypse",
    title: "Apocalypse",
    importance: "medium" as TvArticle['importance'],
    vendu: false,
    image: "/thevertmenthe/artworks/apocalypse.png",
    size: "21 * 29.7 cm",
    technique: "",
    year: "2025",
    notesTop: [],
    notesBottom: [],
  },
  {
    uid: "heavenly",
    title: "Heavenly",
    importance: "medium" as TvArticle['importance'],
    vendu: false,
    image: "/thevertmenthe/artworks/heavenly.png",
    size: "21 * 29.7 cm",
    technique: "",
    year: "2025 ",
    notesTop: [],
    notesBottom: [],
  },
  {
    uid: "dear-bee",
    title: "Dear bee",
    importance: "medium" as TvArticle['importance'],
    vendu: false,
    image: "/thevertmenthe/artworks/dear-bee.png",
    size: "21 * 29.7 cm",
    technique: "",
    year: "2025",
    notesTop: [],
    notesBottom: [],
  },
  {
    uid: "doris",
    title: "Doris",
    importance: "medium" as TvArticle['importance'],
    vendu: false,
    image: "/thevertmenthe/artworks/doris.png",
    size: "21 * 29.7 cm",
    technique: "",
    year: "2025",
    notesTop: [],
    notesBottom: [],
  },
  {
    uid: "nala",
    title: "Nala",
    importance: "medium" as TvArticle['importance'],
    vendu: true,
    image: "/thevertmenthe/artworks/nala.png",
    size: "21 * 29.7 cm",
    technique: "",
    year: "2025",
    notesTop: [],
    notesBottom: [],
  },
  {
    uid: "duvet",
    title: "Duvet",
    importance: "medium" as TvArticle['importance'],
    vendu: false,
    image: "/thevertmenthe/artworks/duvet.png",
    size: "21 * 29.7 cm",
    technique: "",
    year: "2025",
    notesTop: [],
    notesBottom: [],
  },
  {
    uid: "dear-elephant",
    title: "Dear Elephant",
    importance: "medium" as TvArticle['importance'],
    vendu: true,
    image: "/thevertmenthe/artworks/dear-elephant.png",
    size: "21 * 29.7 cm",
    technique: "",
    year: "2025",
    notesTop: [],
    notesBottom: [],
  },
  {
    uid: "starfish",
    title: "Starfish",
    importance: "medium" as TvArticle['importance'],
    vendu: true,
    image: "/thevertmenthe/artworks/starfish.png",
    size: "14.8 * 21 cm",
    technique: "",
    year: "2025",
    notesTop: [],
    notesBottom: [],
  },
  {
    uid: "black-bird",
    title: "Black bird",
    importance: "medium" as TvArticle['importance'],
    vendu: false,
    image: "/thevertmenthe/artworks/black-bird.png",
    size: "21 * 29.7 cm",
    technique: "",
    year: "2025",
    notesTop: [],
    notesBottom: [],
  },
  {
    uid: "friend",
    title: "Friend",
    importance: "medium" as TvArticle['importance'],
    vendu: false,
    image: "/thevertmenthe/artworks/friend.png",
    size: "14.8 * 21 cm",
    technique: "",
    year: "2025",
    notesTop: [],
    notesBottom: [],
  },
  {
    uid: "only-temporary",
    title: "Only temporary",
    importance: "medium" as TvArticle['importance'],
    vendu: false,
    image: "/thevertmenthe/artworks/only-temporary.png",
    size: "21 * 29.7 cm",
    technique: "",
    year: "2025",
    notesTop: [],
    notesBottom: [],
  },
  {
    uid: "heavy",
    title: "Heavy",
    importance: "medium" as TvArticle['importance'],
    vendu: false,
    image: "/thevertmenthe/artworks/heavy.png",
    size: "21 * 29.7 cm",
    technique: "",
    year: "2025",
    notesTop: [],
    notesBottom: [],
  },
  {
    uid: "onizuka",
    title: "Onizuka",
    importance: "medium" as TvArticle['importance'],
    vendu: true,
    image: "/thevertmenthe/artworks/onizuka.png",
    size: "21 * 29.7 cm",
    technique: "",
    year: "2025",
    notesTop: [],
    notesBottom: [],
  },
  {
    uid: "le-g",
    title: "Le G",
    importance: "medium" as TvArticle['importance'],
    vendu: true,
    image: "/thevertmenthe/artworks/le-g.png",
    size: "14.8 * 21 cm",
    technique: "",
    year: "2025",
    notesTop: [],
    notesBottom: [],
  },
  {
    uid: "moonlighting",
    title: "Moonlighting",
    importance: "medium" as TvArticle['importance'],
    vendu: false,
    image: "/thevertmenthe/artworks/moonlighting.png",
    size: "14.8 * 21 cm",
    technique: "",
    year: "2025",
    notesTop: [],
    notesBottom: [],
  },
  {
    uid: "snow-kissed",
    title: "Snow kissed",
    importance: "medium" as TvArticle['importance'],
    vendu: true,
    image: "/thevertmenthe/artworks/snow-kissed.png",
    size: "14.8 * 21 cm",
    technique: "",
    year: "2025",
    notesTop: [],
    notesBottom: [],
  },
]

// Home wall slots, in the original's cadre_controller.000 -> .007 anchor order.
export const TV_HOME_SLOTS = [
  "image_left_bottom",
  "image_left_mid",
  "image_left_mid_loin",
  "image_left_top",
  "image_right_bottom",
  "image_right_mid",
  "image_right_mid_loin",
  "image_right_top",
] as const

// Home wall artwork mapping (Prismic "home" document).
export const TV_HOME_MAP: Record<(typeof TV_HOME_SLOTS)[number], string> = {
  "image_left_bottom": "snow-kissed",
  "image_left_mid": "friend",
  "image_left_mid_loin": "realization",
  "image_left_top": "medieval-journey",
  "image_right_bottom": "only-temporary",
  "image_right_mid": "dear-elephant",
  "image_right_mid_loin": "untilted",
  "image_right_top": "at-eternitys-gates",
}
